on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
       
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: aci-resources
            dns-name-label: jenkins
            image: httpd
           
            name: jenkins
            location: 'central india'

        - name: Run Azure PowerShell script
          uses: azure/powershell@v1
          with:
            azPSVersion: '3.1.0'
            inlineScript: |
              az container create --resource-group aci-resources --name nginxcontainer --image nginx --dns-name-label nginx --ports 80
              az container create --resource-group aci-resources --name ubuntucontainer --image ubuntu --dns-name-label ubuntu
              docker exec -it ubuntucontainer echo "Hello from container!"
              docker exec -it ubuntucontainer apt-get update
              docker exec -it ubuntucontainer apt-get install docker-ce docker-ce-cli containerd.io
              docker exec -it ubuntucontainer docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d -p 80:80 nginx
              docker exec -it ubuntucontainer docker run -dit --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4
              
               