on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
       
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: aci-resources
            dns-name-label: jenkins
            image: httpd
           
            name: jenkins
            location: 'central india'

        - name: Run Azure PowerShell script
          uses: azure/powershell@v1
          with:
            azPSVersion: '3.1.0'
            inlineScript: |
              docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d -p 8080:80 nginx
              az container create --resource-group aci-resources --name nginxcontainer --image nginx --dns-name-label nginx --ports 8080
               